
service: termicadesign-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: prod
  profile: javigonz
  region: us-east-1
  environment:
    tableName: ${self.custom.tableName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: '*'

custom:
  tableName: portolio    

functions:
  getWorks:
    handler: lambdas/endpoints/getWorks.handler
    events:
      - http:
          method: GET
          path: /termicadesignapi
