
service: termicadesign-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: prod
  profile: javigonz
  region: us-east-1
  environment:
    tableName: ${self.custom.tableName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: '*'    

custom:
  tableName: TermicaDesignTable
  apiKeys:
    - name: termicaDesign-ApiKey
      usagePlan:
        name: "termicaDesign-usagePlan"
        description: "Description of first plan"
        quota:
          limit: 1000
          period: MONTH
        throttle:
          burstLimit: 100
          rateLimit: 20

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-add-api-key

functions:
  getWorks:
    handler: lambdas/endpoints/getWorks.handler
    events:
      - http:
          method: GET
          path: /termicadesign-api/get-works
          private: true
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  getWorkById:
    handler: lambdas/endpoints/getWorkById.handler
    events:
      - http:
          method: GET
          path: /termicadesign-api/get-work-by-id/{id} 
          private: true
          cors: true
  setWork:
    handler: lambdas/endpoints/setWork.handler
    events:
      - http:
          method: POST
          path: /termicadesign-api/set-work
          private: true 
          cors: true       
